# Piano Data Exploration and Preparation

## Contents
### Import data set
### Data check
### Normalize Value Columns for Inflation
### Price per instrument columns
### Growth for the Quantity Columns
### Import and merge Production dataset
### Export Dataset

In [1]:
import pandas as pd
import numpy as np
import os

import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt

## Import data set

In [2]:
# path to folder
path = '/Users/susanwang/Documents/Data Projects/DEPianoSales'

In [3]:
# import dataset
df = pd.read_csv(os.path.join(path, 'Data','Piano_Trade_WITS.csv'), index_col=False)

## Data Check

In [4]:
df.head()

,Reporter,Year,Upright Import Trade Value 1000USD,Upright Import Quantity,Grand Import Trade Value 1000USD,Grand Import Quantity,Keyboard Import Trade Value 1000USD,Keyboard Import Quantity,Upright Export Trade Value 1000USD,Upright Export Quantity,Grand Export Trade Value 1000USD,Grand Export Quantity,Keyboard Export Trade Value 1000USD,Keyboard Export Quantity
0,Germany,2000.0,"28,522.00","18,085","14,620.00","1,958","78,763.00","383,406","33,443.00","33,301","53,815.00","11,642","19,769","183,014"
1,Germany,2001.0,"25,409.00","16,011","15,246.00","2,698","69,021.00","251,130","30,429.00","30,887","55,108.00","11,657","21,303","224,581"
2,Germany,2002.0,"25,425.00","16,974","13,106.00","1,920","65,232.00","196,482","35,634.00","36,038","56,807.00","11,765","21,034","257,098"
3,Germany,2003.0,"29,931.00","17,670","13,073.00","1,800","53,624.00","161,518","39,335.00","36,239","68,761.00","15,881","22,098","214,030"
4,Germany,2004.0,"21,976.00","10,810","11,132.00","1,364","42,002.00","107,761","44,223.00","22,360","79,486.00","13,936","35,234","107,094"

In [5]:
df.tail()

,Reporter,Year,Upright Import Trade Value 1000USD,Upright Import Quantity,Grand Import Trade Value 1000USD,Grand Import Quantity,Keyboard Import Trade Value 1000USD,Keyboard Import Quantity,Upright Export Trade Value 1000USD,Upright Export Quantity,Grand Export Trade Value 1000USD,Grand Export Quantity,Keyboard Export Trade Value 1000USD,Keyboard Export Quantity
23,Germany,2023.0,"33,859.91","9,878","32,305.90","2,472","172,225.11","298,469","48,108.81","7,015","173,393.64","3,634","165,321","223,037"
24,Germany,2024.0,"21,018.70","6,558","25,245.36","1,876","176,079.88","336,050","35,208.41","5,728","122,108.03","2,659","163,885","225,301"
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.shape

(28, 14)

In [7]:
# remove NaN rows
df.dropna(inplace=True)

In [8]:
df.shape

(25, 14)

In [9]:
df.tail()

,Reporter,Year,Upright Import Trade Value 1000USD,Upright Import Quantity,Grand Import Trade Value 1000USD,Grand Import Quantity,Keyboard Import Trade Value 1000USD,Keyboard Import Quantity,Upright Export Trade Value 1000USD,Upright Export Quantity,Grand Export Trade Value 1000USD,Grand Export Quantity,Keyboard Export Trade Value 1000USD,Keyboard Export Quantity
20,Germany,2020.0,"31,922.61","11,537","25,202.75","2,208","195,388.63","440,943","43,534.34","7,686","118,911.25","2,975","126,610","182,046"
21,Germany,2021.0,"40,276.08","13,993","30,787.64","2,542","242,659.50","520,304","58,646.58","9,364","157,224.55","3,775","147,143","227,169"
22,Germany,2022.0,"42,079.21","14,680","31,100.05","2,624","228,745.85","416,152","55,036.27","8,569","150,018.23","3,563","162,407","228,862"
23,Germany,2023.0,"33,859.91","9,878","32,305.90","2,472","172,225.11","298,469","48,108.81","7,015","173,393.64","3,634","165,321","223,037"
24,Germany,2024.0,"21,018.70","6,558","25,245.36","1,876","176,079.88","336,050","35,208.41","5,728","122,108.03","2,659","163,885","225,301"

In [10]:
df.dtypes

Reporter                                  object
Year                                     float64
 Upright Import Trade Value 1000USD       object
 Upright Import Quantity                  object
 Grand Import Trade Value 1000USD         object
Grand Import Quantity                     object
 Keyboard Import Trade Value 1000USD      object
 Keyboard Import Quantity                 object
 Upright Export Trade Value 1000USD       object
 Upright Export Quantity                  object
 Grand Export Trade Value 1000USD         object
 Grand Export Quantity                    object
Keyboard Export Trade Value 1000USD       object
Keyboard Export Quantity                  object
dtype: object

In [11]:
# drop reporter column
df.drop(columns='Reporter', inplace=True)

In [12]:
# random spaces in columns
df.columns

Index(['Year', ' Upright Import Trade Value 1000USD ',
       ' Upright Import Quantity ', ' Grand Import Trade Value 1000USD ',
       'Grand Import Quantity', ' Keyboard Import Trade Value 1000USD ',
       ' Keyboard Import Quantity ', ' Upright Export Trade Value 1000USD ',
       ' Upright Export Quantity ', ' Grand Export Trade Value 1000USD ',
       ' Grand Export Quantity ', 'Keyboard Export Trade Value 1000USD',
       'Keyboard Export Quantity'],
      dtype='object')

In [13]:
df.columns = df.columns.str.strip()
df.columns

Index(['Year', 'Upright Import Trade Value 1000USD', 'Upright Import Quantity',
       'Grand Import Trade Value 1000USD', 'Grand Import Quantity',
       'Keyboard Import Trade Value 1000USD', 'Keyboard Import Quantity',
       'Upright Export Trade Value 1000USD', 'Upright Export Quantity',
       'Grand Export Trade Value 1000USD', 'Grand Export Quantity',
       'Keyboard Export Trade Value 1000USD', 'Keyboard Export Quantity'],
      dtype='object')

In [14]:
num_columns = df.columns[1:]
print(num_columns)

Index(['Upright Import Trade Value 1000USD', 'Upright Import Quantity',
       'Grand Import Trade Value 1000USD', 'Grand Import Quantity',
       'Keyboard Import Trade Value 1000USD', 'Keyboard Import Quantity',
       'Upright Export Trade Value 1000USD', 'Upright Export Quantity',
       'Grand Export Trade Value 1000USD', 'Grand Export Quantity',
       'Keyboard Export Trade Value 1000USD', 'Keyboard Export Quantity'],
      dtype='object')

In [15]:
# change to numeric dtype
for col in num_columns:
    df[col] = df[col].str.replace(',', '')
    df[col] = pd.to_numeric(df[col])

In [16]:
df.dtypes

Year                                   float64
Upright Import Trade Value 1000USD     float64
Upright Import Quantity                  int64
Grand Import Trade Value 1000USD       float64
Grand Import Quantity                    int64
Keyboard Import Trade Value 1000USD    float64
Keyboard Import Quantity                 int64
Upright Export Trade Value 1000USD     float64
Upright Export Quantity                  int64
Grand Export Trade Value 1000USD       float64
Grand Export Quantity                    int64
Keyboard Export Trade Value 1000USD      int64
Keyboard Export Quantity                 int64
dtype: object

In [17]:
df.head()

,Year,Upright Import Trade Value 1000USD,Upright Import Quantity,Grand Import Trade Value 1000USD,Grand Import Quantity,Keyboard Import Trade Value 1000USD,Keyboard Import Quantity,Upright Export Trade Value 1000USD,Upright Export Quantity,Grand Export Trade Value 1000USD,Grand Export Quantity,Keyboard Export Trade Value 1000USD,Keyboard Export Quantity
0,2000.0,28522.0,18085,14620.0,1958,78763.0,383406,33443.0,33301,53815.0,11642,19769,183014
1,2001.0,25409.0,16011,15246.0,2698,69021.0,251130,30429.0,30887,55108.0,11657,21303,224581
2,2002.0,25425.0,16974,13106.0,1920,65232.0,196482,35634.0,36038,56807.0,11765,21034,257098
3,2003.0,29931.0,17670,13073.0,1800,53624.0,161518,39335.0,36239,68761.0,15881,22098,214030
4,2004.0,21976.0,10810,11132.0,1364,42002.0,107761,44223.0,22360,79486.0,13936,35234,107094

In [18]:
# year col to integer
df['Year'] = df['Year'].astype('int64')
df.head()

,Year,Upright Import Trade Value 1000USD,Upright Import Quantity,Grand Import Trade Value 1000USD,Grand Import Quantity,Keyboard Import Trade Value 1000USD,Keyboard Import Quantity,Upright Export Trade Value 1000USD,Upright Export Quantity,Grand Export Trade Value 1000USD,Grand Export Quantity,Keyboard Export Trade Value 1000USD,Keyboard Export Quantity
0,2000,28522.0,18085,14620.0,1958,78763.0,383406,33443.0,33301,53815.0,11642,19769,183014
1,2001,25409.0,16011,15246.0,2698,69021.0,251130,30429.0,30887,55108.0,11657,21303,224581
2,2002,25425.0,16974,13106.0,1920,65232.0,196482,35634.0,36038,56807.0,11765,21034,257098
3,2003,29931.0,17670,13073.0,1800,53624.0,161518,39335.0,36239,68761.0,15881,22098,214030
4,2004,21976.0,10810,11132.0,1364,42002.0,107761,44223.0,22360,79486.0,13936,35234,107094

## Normalize Trade Values for Inflation

In [19]:
# import inflation dataset
infl = pd.read_csv(os.path.join(path, 'Data', 'us_cpi_u.csv'), index_col=False)

In [20]:
infl

    Year  CPI_U
0   2000  172.2
1   2001  177.1
2   2002  179.9
3   2003  184.0
4   2004  188.9
5   2005  195.3
6   2006  201.6
7   2007  207.3
8   2008  215.3
9   2009  214.5
10  2010  218.1
11  2011  224.9
12  2012  229.6
13  2013  232.9
14  2014  236.7
15  2015  237.0
16  2016  240.0
17  2017  245.1
18  2018  251.1
19  2019  255.7
20  2020  258.8
21  2021  271.0
22  2022  292.7
23  2023  304.7
24  2024  313.7
25  2025  320.3

In [21]:
# merge with main df
df1 = df.merge(infl, how='left', on='Year')
df1.head()

,Year,Upright Import Trade Value 1000USD,Upright Import Quantity,Grand Import Trade Value 1000USD,Grand Import Quantity,Keyboard Import Trade Value 1000USD,Keyboard Import Quantity,Upright Export Trade Value 1000USD,Upright Export Quantity,Grand Export Trade Value 1000USD,Grand Export Quantity,Keyboard Export Trade Value 1000USD,Keyboard Export Quantity,CPI_U
0,2000,28522.0,18085,14620.0,1958,78763.0,383406,33443.0,33301,53815.0,11642,19769,183014,172.2
1,2001,25409.0,16011,15246.0,2698,69021.0,251130,30429.0,30887,55108.0,11657,21303,224581,177.1
2,2002,25425.0,16974,13106.0,1920,65232.0,196482,35634.0,36038,56807.0,11765,21034,257098,179.9
3,2003,29931.0,17670,13073.0,1800,53624.0,161518,39335.0,36239,68761.0,15881,22098,214030,184.0
4,2004,21976.0,10810,11132.0,1364,42002.0,107761,44223.0,22360,79486.0,13936,35234,107094,188.9

In [22]:
df1.tail()

,Year,Upright Import Trade Value 1000USD,Upright Import Quantity,Grand Import Trade Value 1000USD,Grand Import Quantity,Keyboard Import Trade Value 1000USD,Keyboard Import Quantity,Upright Export Trade Value 1000USD,Upright Export Quantity,Grand Export Trade Value 1000USD,Grand Export Quantity,Keyboard Export Trade Value 1000USD,Keyboard Export Quantity,CPI_U
20,2020,31922.61,11537,25202.75,2208,195388.63,440943,43534.34,7686,118911.25,2975,126610,182046,258.8
21,2021,40276.08,13993,30787.64,2542,242659.50,520304,58646.58,9364,157224.55,3775,147143,227169,271.0
22,2022,42079.21,14680,31100.05,2624,228745.85,416152,55036.27,8569,150018.23,3563,162407,228862,292.7
23,2023,33859.91,9878,32305.90,2472,172225.11,298469,48108.81,7015,173393.64,3634,165321,223037,304.7
24,2024,21018.70,6558,25245.36,1876,176079.88,336050,35208.41,5728,122108.03,2659,163885,225301,313.7

In [23]:
# create new columns for all trade values with inflation calcuation for year 2024
# price_2024 = price_year * (313.7/ cpi_year)
df1['Upright Import Trade Value'] = (df1['Upright Import Trade Value 1000USD']*(313.7/ df1['CPI_U'])).round(2)
df1['Grand Import Trade Value'] = (df1['Grand Import Trade Value 1000USD']*(313.7/ df1['CPI_U'])).round(2)
df1['Keyboard Import Trade Value'] = (df1['Keyboard Import Trade Value 1000USD']*(313.7/ df1['CPI_U'])).round(2)

df1['Upright Export Trade Value'] = (df1['Upright Export Trade Value 1000USD']*(313.7/ df1['CPI_U'])).round(2)
df1['Grand Export Trade Value'] = (df1['Grand Export Trade Value 1000USD']*(313.7/ df1['CPI_U'])).round(2)
df1['Keyboard Export Trade Value'] = (df1['Keyboard Export Trade Value 1000USD']*(313.7/ df1['CPI_U'])).round(2)

In [24]:
df1.head()

,Year,Upright Import Trade Value 1000USD,Upright Import Quantity,Grand Import Trade Value 1000USD,Grand Import Quantity,Keyboard Import Trade Value 1000USD,Keyboard Import Quantity,Upright Export Trade Value 1000USD,Upright Export Quantity,Grand Export Trade Value 1000USD,Grand Export Quantity,Keyboard Export Trade Value 1000USD,Keyboard Export Quantity,CPI_U,Upright Import Trade Value,Grand Import Trade Value,Keyboard Import Trade Value,Upright Export Trade Value,Grand Export Trade Value,Keyboard Export Trade Value
0,2000,28522.0,18085,14620.0,1958,78763.0,383406,33443.0,33301,53815.0,11642,19769,183014,172.2,51959.07,26633.53,143484.05,60923.75,98035.80,36013.56
1,2001,25409.0,16011,15246.0,2698,69021.0,251130,30429.0,30887,55108.0,11657,21303,224581,177.1,45007.36,27005.48,122257.98,53899.36,97613.66,37734.34
2,2002,25425.0,16974,13106.0,1920,65232.0,196482,35634.0,36038,56807.0,11765,21034,257098,179.9,44334.76,22853.54,113748.07,62136.66,99057.01,36677.96
3,2003,29931.0,17670,13073.0,1800,53624.0,161518,39335.0,36239,68761.0,15881,22098,214030,184.0,51029.10,22288.04,91423.09,67061.90,117230.03,37674.69
4,2004,21976.0,10810,11132.0,1364,42002.0,107761,44223.0,22360,79486.0,13936,35234,107094,188.9,36494.82,18486.55,69751.34,73439.68,131999.78,58511.94

In [25]:
# remove original trade value columns
keep = list()
for col in df1.columns:
    if '1000USD' not in col:
        keep.append(col)
keep.remove('CPI_U')
print(keep)

['Year', 'Upright Import Quantity', 'Grand Import Quantity', 'Keyboard Import Quantity', 'Upright Export Quantity', 'Grand Export Quantity', 'Keyboard Export Quantity', 'Upright Import Trade Value', 'Grand Import Trade Value', 'Keyboard Import Trade Value', 'Upright Export Trade Value', 'Grand Export Trade Value', 'Keyboard Export Trade Value']

In [26]:
df2 = df1[keep].copy()
df2.head()

,Year,Upright Import Quantity,Grand Import Quantity,Keyboard Import Quantity,Upright Export Quantity,Grand Export Quantity,Keyboard Export Quantity,Upright Import Trade Value,Grand Import Trade Value,Keyboard Import Trade Value,Upright Export Trade Value,Grand Export Trade Value,Keyboard Export Trade Value
0,2000,18085,1958,383406,33301,11642,183014,51959.07,26633.53,143484.05,60923.75,98035.80,36013.56
1,2001,16011,2698,251130,30887,11657,224581,45007.36,27005.48,122257.98,53899.36,97613.66,37734.34
2,2002,16974,1920,196482,36038,11765,257098,44334.76,22853.54,113748.07,62136.66,99057.01,36677.96
3,2003,17670,1800,161518,36239,15881,214030,51029.10,22288.04,91423.09,67061.90,117230.03,37674.69
4,2004,10810,1364,107761,22360,13936,107094,36494.82,18486.55,69751.34,73439.68,131999.78,58511.94

## Price per instrument columns

In [27]:
df2['Upright Import Price'] = df2['Upright Import Trade Value']/df2['Upright Import Quantity']
df2['Grand Import Price'] = df2['Grand Import Trade Value']/df2['Grand Import Quantity']
df2['Keyboard Import Price'] = df2['Keyboard Import Trade Value']/df2['Keyboard Import Quantity']

df2['Upright Export Price'] = df2['Upright Export Trade Value']/df2['Upright Export Quantity']
df2['Grand Export Price'] = df2['Grand Export Trade Value']/df2['Grand Export Quantity']
df2['Keyboard Export Price'] = df2['Keyboard Export Trade Value']/df2['Keyboard Export Quantity']

In [28]:
df2.head()

,Year,Upright Import Quantity,Grand Import Quantity,Keyboard Import Quantity,Upright Export Quantity,Grand Export Quantity,Keyboard Export Quantity,Upright Import Trade Value,Grand Import Trade Value,Keyboard Import Trade Value,Upright Export Trade Value,Grand Export Trade Value,Keyboard Export Trade Value,Upright Import Price,Grand Import Price,Keyboard Import Price,Upright Export Price,Grand Export Price,Keyboard Export Price
0,2000,18085,1958,383406,33301,11642,183014,51959.07,26633.53,143484.05,60923.75,98035.80,36013.56,2.873048,13.602416,0.374235,1.829487,8.420873,0.196780
1,2001,16011,2698,251130,30887,11657,224581,45007.36,27005.48,122257.98,53899.36,97613.66,37734.34,2.811027,10.009444,0.486831,1.745050,8.373823,0.168021
2,2002,16974,1920,196482,36038,11765,257098,44334.76,22853.54,113748.07,62136.66,99057.01,36677.96,2.611922,11.902885,0.578924,1.724198,8.419635,0.142661
3,2003,17670,1800,161518,36239,15881,214030,51029.10,22288.04,91423.09,67061.90,117230.03,37674.69,2.887895,12.382244,0.566024,1.850545,7.381779,0.176025
4,2004,10810,1364,107761,22360,13936,107094,36494.82,18486.55,69751.34,73439.68,131999.78,58511.94,3.376024,13.553189,0.647278,3.284422,9.471856,0.546361

## Import and add production data set

In [29]:
# production data set
prod = pd.read_csv(os.path.join(path, 'Data', 'Piano_Production.csv'), index_col=False)

In [30]:
prod

,Jahr,Prod Upright Euro,Prod Upright Stück,Prod Grand Euro,Prod Grand Stück
0,2006,35655.00,6452,74515.00,2599
1,2010,23742.00,4034,51601.00,1734
2,2011,26438.50,3304,57469.50,2117
3,2012,29135.00,2574,63338.00,2499
4,2013,28168.00,3269,68982.00,2531
5,2014,27201.00,3964,74626.00,2563
6,2015,28637.00,3699,74804.00,1996
7,2016,28796.25,3630,79010.25,2022
8,2017,28955.50,3562,83216.50,2049
9,2018,29114.75,3493,87422.75,2075
10,2019,29274.00,3424,91629.00,2101
11,2020,28370.00,3282,83450.00,1927
12,2021,32257.00,3532,99545.00,2156
13,2022,36026.00,3627,110519.00,2228
14,2023,29477.00,2410,122217.00,2190
15,2024,18028.00,1336,110422.00,1286
16,2025,11707.00,985,56729.00,687

In [31]:
# rename columns
prod.rename(columns={'Jahr': 'Year', 
                     'Prod Upright Stück': 'Upright Prod Quantity', 
                     'Prod Grand Stück': 'Grand Prod Quantity'}, inplace=True)
prod.head()

,Year,Prod Upright Euro,Upright Prod Quantity,Prod Grand Euro,Grand Prod Quantity
0,2006,35655.0,6452,74515.0,2599
1,2010,23742.0,4034,51601.0,1734
2,2011,26438.5,3304,57469.5,2117
3,2012,29135.0,2574,63338.0,2499
4,2013,28168.0,3269,68982.0,2531

In [32]:
prod.dtypes

Year                       int64
Prod Upright Euro        float64
Upright Prod Quantity      int64
Prod Grand Euro          float64
Grand Prod Quantity        int64
dtype: object

In [33]:
prod

,Year,Prod Upright Euro,Upright Prod Quantity,Prod Grand Euro,Grand Prod Quantity
0,2006,35655.00,6452,74515.00,2599
1,2010,23742.00,4034,51601.00,1734
2,2011,26438.50,3304,57469.50,2117
3,2012,29135.00,2574,63338.00,2499
4,2013,28168.00,3269,68982.00,2531
5,2014,27201.00,3964,74626.00,2563
6,2015,28637.00,3699,74804.00,1996
7,2016,28796.25,3630,79010.25,2022
8,2017,28955.50,3562,83216.50,2049
9,2018,29114.75,3493,87422.75,2075
10,2019,29274.00,3424,91629.00,2101
11,2020,28370.00,3282,83450.00,1927
12,2021,32257.00,3532,99545.00,2156
13,2022,36026.00,3627,110519.00,2228
14,2023,29477.00,2410,122217.00,2190
15,2024,18028.00,1336,110422.00,1286
16,2025,11707.00,985,56729.00,687

In [34]:
prod.isna().any()

Year                     False
Prod Upright Euro        False
Upright Prod Quantity    False
Prod Grand Euro          False
Grand Prod Quantity      False
dtype: bool

In [35]:
# merge
df3 = df2.merge(prod, how='left', on='Year')
df3.tail()

,Year,Upright Import Quantity,Grand Import Quantity,Keyboard Import Quantity,Upright Export Quantity,Grand Export Quantity,Keyboard Export Quantity,Upright Import Trade Value,Grand Import Trade Value,Keyboard Import Trade Value,...,Upright Import Price,Grand Import Price,Keyboard Import Price,Upright Export Price,Grand Export Price,Keyboard Export Price,Prod Upright Euro,Upright Prod Quantity,Prod Grand Euro,Grand Prod Quantity
20,2020,11537,2208,440943,7686,2975,182046,38694.45,30549.08,236836.99,...,3.353944,13.835634,0.537115,6.865653,48.449156,0.843019,28370.0,3282.0,83450.0,1927.0
21,2021,13993,2542,520304,9364,3775,227169,46622.16,35638.68,280894.04,...,3.331820,14.019937,0.539865,7.249808,48.211277,0.749783,32257.0,3532.0,99545.0,2156.0
22,2022,14680,2624,416152,8569,3563,228862,45098.22,33331.35,245157.41,...,3.072086,12.702496,0.589105,6.883521,45.125290,0.760541,36026.0,3627.0,110519.0,2228.0
23,2023,9878,2472,298469,7015,3634,223037,34860.04,33260.13,177312.17,...,3.529059,13.454745,0.594072,7.060557,49.123613,0.763121,29477.0,2410.0,122217.0,2190.0
24,2024,6558,1876,336050,5728,2659,225301,21018.70,25245.36,176079.88,...,3.205047,13.457015,0.523969,6.146720,45.922539,0.727405,18028.0,1336.0,110422.0,1286.0

In [36]:
df3.head()

,Year,Upright Import Quantity,Grand Import Quantity,Keyboard Import Quantity,Upright Export Quantity,Grand Export Quantity,Keyboard Export Quantity,Upright Import Trade Value,Grand Import Trade Value,Keyboard Import Trade Value,...,Upright Import Price,Grand Import Price,Keyboard Import Price,Upright Export Price,Grand Export Price,Keyboard Export Price,Prod Upright Euro,Upright Prod Quantity,Prod Grand Euro,Grand Prod Quantity
0,2000,18085,1958,383406,33301,11642,183014,51959.07,26633.53,143484.05,...,2.873048,13.602416,0.374235,1.829487,8.420873,0.196780,NaN,NaN,NaN,NaN
1,2001,16011,2698,251130,30887,11657,224581,45007.36,27005.48,122257.98,...,2.811027,10.009444,0.486831,1.745050,8.373823,0.168021,NaN,NaN,NaN,NaN
2,2002,16974,1920,196482,36038,11765,257098,44334.76,22853.54,113748.07,...,2.611922,11.902885,0.578924,1.724198,8.419635,0.142661,NaN,NaN,NaN,NaN
3,2003,17670,1800,161518,36239,15881,214030,51029.10,22288.04,91423.09,...,2.887895,12.382244,0.566024,1.850545,7.381779,0.176025,NaN,NaN,NaN,NaN
4,2004,10810,1364,107761,22360,13936,107094,36494.82,18486.55,69751.34,...,3.376024,13.553189,0.647278,3.284422,9.471856,0.546361,NaN,NaN,NaN,NaN

## Export dataset

In [37]:
df3.to_csv(os.path.join(path, 'Data', 'merged_df.csv'), index=False)